
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module mp1(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// GPIO_1, GPIO_1 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO,
	
	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

MiniLab1 ML1(.KEY(KEY), .CLOCK_50(CLOCK_50), .LEDR(LEDR), .SW(), .TX(GPIO[3]), .RX(GPIO[5]));


//=======================================================
//  Structural coding
//=======================================================



endmodule
